# -*- coding: utf-8 -*-
"""Master-Python-Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JDwiw1slXjID7R6evJjhy2AQURYzquab

##### Create list by List Comprehension
"""

mylist = [_ for _ in "ABCDEFGHIJKLM"]
mylist

"""##### Adds an item at the end of the list --> append()"""

mylist.append([100, 200])
mylist

"""##### Add the items of a iterable, to the end of the current list --> extend()"""

mylist.extend("THIS")
print(mylist)

"""##### Add an item at the specified position --> insert()"""

mylist.insert(1, 20.35)
print(mylist)

"""##### Remove the first occurence of specified item --> remove()"""

mylist.remove("H")
print(mylist)

"""##### Removes the item at the specified position --> pop(index)"""

mylist.pop(-5)

"""##### Removes the item at the end of the list --> pop()"""

mylist.pop()

"""##### Get the index of the first occurence of the specified item --> index()"""

mylist.index("I")

"""##### Reverse the order of the list --> reverse()"""

mylist.reverse()
print(mylist)

"""##### Get the number of occurences of the specified item"""

mylist.count("I")

"""##### Sort the list --> sort()"""

# As comparison can not happen between string and float, let's remove the float value
mylist.remove(20.35)
mylist.sort()
print(mylist)

"""##### Check if item is present in the list --> **`in`**"""

"T" in mylist

"""##### Check if an item is not present in the list --> **`not in`**"""

20.35 not in mylist

"""##### Create a new list by copying **`mylist`** --> copy()"""

newlist = mylist.copy()
print(newlist)

"""##### Getting index and items at those indexes from the list"""

for idx in range(0,len(mylist)):
  print(f"mylist[{idx}] = {mylist[idx]}")

"""##### Get Reverse Indexing index"""

import numpy as np
for idx in list(np.arange(len(mylist),0,-1)*-1):
  print(f"mylist[{idx}] = {mylist[idx]}")

"""##### Get the length of the list --> `len(name_of_list)`"""

len(mylist)

"""##### Remove all items from the list --> clear()"""

mylist.clear()
print(mylist)

"""##### Delete the list --> `del(name_of_list)`"""

del(mylist)

##### Thank you for reading